default: &default
  adapter: postgresql
  pool: 5

  database: test_project
  encoding: UTF-8
  username: root
  password: postgres
  host: localhost


development:
  <<: *default

test:
  <<: *default
  database: test_project_for_test

production:
  <<: *default