default: &default
  adapter: mysql2
  database: test_project
  pool: 5
  timeout: 5000
  username: root

development:
  <<: *default

test:
  <<: *default
  database: test_project_for_test

production:
  <<: *default